### ISSUE TITLE
create unified Bulletin Board

### ISSUE THREAD

**Issue by reviser273** [elmo/upstairs#114]
what is now listed as Classifieds, Recent Ads, and others should all be part of one unified Bulletin Board feature on the Community page. 

Any posting that is open to the whole community should go on the Bulletin Board. User will see highlights of that on the Community Page.

**Comment by elmo** [comment]
Are you saying that we should intermix "posts" "with "classifieds' and "tickets" as one general feed like Facebook?

**Comment by reviser273** [comment]
No. I'm thinking that the Bulletin Board has different sections. On NextDoor, what I'm calling the Bulletin Board is basically the entire site. Look at how many posts I see as soon as I land on this page, and how the BB's sections are organized on the LH nav: 

https://foresthillca.nextdoor.com/classifieds/
