### ISSUE TITLE
Add a photo is outta line

### ISSUE THREAD

**Issue by luvmodern** [elmo/upstairs#130]

**Comment by luvmodern** [comment]
![screen shot 2015-06-04 at 2 31 52 pm](https://cloud.githubusercontent.com/assets/11860564/7994957/7e89eb2c-0ac6-11e5-8e97-f70444308b21.png)

**Comment by elmo** [comment]
![image](https://cloud.githubusercontent.com/assets/13116/8020803/f22e5a74-0c3b-11e5-9a66-8e2b4f933261.png)

Fixed.
