### ISSUE TITLE
What does "join" mean?

### ISSUE THREAD

**Issue by luvmodern** [elmo/upstairs#132]

**Comment by luvmodern** [comment]
![screen shot 2015-06-04 at 2 40 14 pm](https://cloud.githubusercontent.com/assets/11860564/7995078/b0a27dd0-0ac7-11e5-84e4-2aa19d2105b5.png)

**Comment by elmo** [comment]
You should only get that message if you are not a member of a community.

Should non-member be allowed to see the community page?  I don't think so.  We can discuss.
