### ISSUE TITLE
Design profile login profile menu.  Connected to #166

### ISSUE THREAD

**Issue by elmo** [elmo/upstairs#167]

**Comment by elmo** [comment]
![image](https://cloud.githubusercontent.com/assets/13116/8273029/8f7680c4-1810-11e5-865a-e220c8500957.png)

**Comment by elmo** [comment]
Connected to #166

**Comment by espilacopa** [comment]
![image](https://cloud.githubusercontent.com/assets/3173319/8273041/ed11f81c-1810-11e5-9150-5d787066354b.png)

**Comment by elmo** [comment]
![image](https://cloud.githubusercontent.com/assets/13116/8273042/f62ba2ae-1810-11e5-86d1-051a2462c3b1.png)
