### ISSUE TITLE
make list of all email communications

### ISSUE THREAD

**Issue by elmo** [elmo/upstairs#23]
Figure out what emails need to be sent when and what the copy should be.

**Comment by luvmodern** [comment]
We need automatic emails for creating an account and alerts when someone in their building posts a message to the community or just to them individually. Perhaps we make these daily digests?

**Comment by luvmodern** [comment]
This has been assigned to Michael.

Welcome email - user just created an account
Verify your listing - user created an account and claimed an address
Daily digest - this will include all emails from the building for the day
Alerts - alert if the landlord contacted you
change password - copy for changing password
