### ISSUE TITLE
Decide on username

### ISSUE THREAD

**Issue by elmo** [elmo/upstairs#76]
Username -- this is the classic question facing any social network: real names or not? It’s a hell of a lot better if you can get people to give you their real name. But our interests aside, what’s more useful for a building that wants to organize itself into a private community on these boards? Seems to me that social grouping wants real names too -- although it also wants an anonymous comment function. But if we are planning on building a little society here that will all be living together in the building and in an Upstairs “building” for years to come, I really think we should think about asking for real names. We want people to be able to do carpool commuting, local buy/sell markets, babysitting, etc -- how can this community we want to build not use real names?

**Comment by reviser273** [comment]
We've agreed that we should encourage real names (by giving them extra functionality, maybe?) but not demand them?

**Comment by reviser273** [comment]
Yes, we've agreed. I think we can retire this one.
