### ISSUE TITLE
Collect address upon sign-up

### ISSUE THREAD

**Issue by elmo** [elmo/upstairs#81]
From Michael:

And shouldn’t address be part of this first page? Can I join Upstairs without being part of an address?

For that matter, what happens when a user goes to sign up for an address that has already been registered? 

And what happens when someone is the first to sign up for an address? Do we ask them for email addresses to send building invites to? We’ll need all that copy, including the standard invite.

**Comment by elmo** [comment]
For that matter, what happens when a user goes to sign up for an address that has already been registered? 

And what happens when someone is the first to sign up for an address? Do we ask them for email addresses to send building invites to? We’ll need all that copy, including the standard invite.

**Comment by elmo** [comment]
There's a conceptual difference between an "address" and an "community".  Take my example:

My address is 401 43rd Avenue Apt 306  (sf,ca,94121)
My community is 401 43rd Avenue

In theory, we could a community as small as an individual apartment 401 43rd Avenue Apt 306.  This would make sense if I had a bunch of roommates.   In this example, I could belong to two communites: 1. my apartment, 2. my building.

**Comment by reviser273** [comment]
This is a really interesting point which nails how we define Communities. Is it reflected in product yet? I will now, in teaching myself Waffle, attempt to create an item and assign it to myself to name Communities.

**Comment by reviser273** [comment]
As noted, I think we should call them Buildings. Really nail down what this is intended to be for, and be like.
